shared:
  - &chat-alert
    author_name: cycloid.io
    author_link: https://www.cycloid.io/
    title_link: ((cycloid_console_url))/organizations/((organization))/projects/((project))/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_ID
    fields:
      - title: Project
        value: ((project))
        short: true
      - title: Environment
        value: ((env))
        short: true

groups:
  - name: overview
    jobs:
      - bump-cli-with-be

resource_types:
  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
      registry_mirror:
        host: registry-mirror.owl.cycloid.io

resources:
  - name: git_api_tag
    type: git
    icon: git
    source:
      uri: ((git_api_uri))
      branch: ((git_api_branch))
      private_key: ((git_private_key))
      fetch_tags: yes
      tag_regex: 'v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+'

  - name: git_cli
    type: git
    icon: git
    source:
      uri: ((git_cli_uri))
      branch: ((git_cli_branch))
      private_key: ((git_private_key))

  # to avoid the use of new branches commit in future get
  #- name: git_cli_bump
  #  type: git
  #  source:
  #    branch: ((git_cli_branch))
  #    private_key: ((git_github.ssh_key))
  #    uri: ((git_cli_uri))
  #  icon: git

  # create chat alert in zulip development channel
  - name: chat_alert
    type: slack-notification
    icon: slack
    source:
      url: ((slack_webhook))

jobs:
  - name: bump-cli-with-be
    build_logs_to_retain: 10
    plan:
      - do:
          - get: git_api_tag
            trigger: true

          - get: git_cli

          - put: chat_alert
            params:
              attachments:
                - <<: *chat-alert
                  title: "[ New API version detected: PR in progess...]"
                  fallback: "start - DEPLOY of ((project))/((env)) [In progress ...]"
                  color: "#039BE5"

          - task: generate-swagger-client
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: quay.io/goswagger/swagger
                  tag: v0.21.0
              run:
                path: /bin/sh
                args:
                  - '-exc'
                  - |
                    DIR=${PWD}
                    cd cli_code/

                    # generates client using latest swagger in API
                    cp ${DIR}/api_code/swagger.yml .
                    make generate-client

                    # change the client version to match the api tag release
                    export SWAGGER_VERSION=$(cd ${DIR}/api_code && git describe) 
                    echo ${SWAGGER_VERSION} > client/version

                    # configure git        
                    git config --global user.email "devops@cycloid.io"
                    git config --global user.name "Cycloid"

                    # creates new branch to use to create commit
                    git checkout -b ${SWAGGER_VERSION}
                    git add client
                    git commit -m "Bump swagger client to version ${SWAGGER_VERSION}"
                    git push -u origin head
              params:
                GOPATH: '/go'
              inputs:
                - name: git_api_tag
                  path: api_code
                - name: git_cli
                  path: cli_code
              outputs:
                - name: cli_with_commit
                  path: cli_code
                  
    on_success:
      - put: chat_alert
        params:
          attachments:
            - <<: *chat-alert
              title: "[SUCCESS]"
              fallback: "end - PR created at ((github_repo_name)) [SUCCESS]"
              color: good
     
    on_failure:
      - put: chat_alert
        params:
          attachments:
            - <<: *chat-alert
              title: "[FAIL]"
              fallback: "end - PR not created at ((github_repo_name)) [FAIL]"
              color: danger

    on_abort:
      - put: chat_alert
        params:
          attachments:
            - <<: *chat-alert
              title: "[ABORT]"
              fallback: "end - PR not created at ((github_repo_name)) [ABORT]"
              color: "#039BE5"

          #- put: git_cli_bump
          #  params:
          #    branch: cli_bump
          #    repository: cli_with_commit
